File: justfile
set allow-duplicate-recipes := true
set ignore-comments := true

_default:
    #!/usr/bin/bash
    source /usr/lib/ujust/libformatting.sh
    echo "$(Urllink "https://docs.projectbluefin.io/administration#community-aliases-and-workarounds" "Click here to view the Universal Blue just documentation")"
    /usr/bin/ujust --list --list-heading $'Available commands:\n' --list-prefix $' - '

# Imports
import "/usr/share/ublue-os/just/00-default.just"
import "/usr/share/ublue-os/just/10-update.just"
import "/usr/share/ublue-os/just/15-luks.just"
import "/usr/share/ublue-os/just/20-clean.just"
import "/usr/share/ublue-os/just/30-distrobox.just"
import "/usr/share/ublue-os/just/40-nvidia.just"
import "/usr/share/ublue-os/just/50-akmods.just"
import "/usr/share/dune-os/just/dune.just"

